name: Publish NuGet Package

on:
  workflow_dispatch:

jobs:
  build-and-publish:
      runs-on: ubuntu-latest
      environment: nuget
      steps:
        - uses: actions/checkout@v3
        
        - name: Setup .NET 9.0 SDK
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '9.0.x'
  
        - name: Restore dependencies
          run: dotnet restore
  
        - name: Build
          run: dotnet build --configuration Release
  
        - name: Pack
          run: dotnet pack --configuration Release --output ./nupkg
  
        - name: Push to GitHub Packages
          run: dotnet nuget push ./nupkg/*.nupkg --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_API_KEY }}
